server:
  port: 17070
spring:
  mvc:
      view:
        prefix:  /pages/
  datasource:
    url: jdbc:mysql://localhost:3306?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver